#!/bin/bash
set -e

sourcedir="$1"
url="$2"
workdir=$(mktemp -d)
pushd $workdir

trap "popd; rm -f $workdir" EXIT

for f in bufr default
do
    curl -sS $url/$f.lua > $f.lua
    luac -o $f.lua $f
done

mv {bufr,default}.lua{,c} $sourcedir/
