name: RPM build

on:
  # Build only on pushes into master branch
  push:
    branches: [master]


jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  rpm-build:
    container: fedora:32
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script
        run: ./.travis-build.sh
        shell: bash
