name: RPM build

on:
  push:
    branches: [master, ghci]


jobs:
  rpm-build:
    container: fedora:32
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: dnf install -y git
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script
        run: ./.travis-build.sh fedora:32
        shell: bash
