name: RPM build

on:
  push:
    tags: ["v*.*.*"]

jobs:
  rpm-build:
    container: centos:8
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: dnf install -y git
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script
        run: ./.travis-build.sh centos:8
        shell: bash

      - name: Install API token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: echo "$API_TOKEN_CONTENT" > ".copr"

      - name: Submit the build to copr
        run: |
          dnf install -y copr-cli
          copr-cli --config .copr build --nowait simc/stable fedora/SPECS/meteo-vm2.spec
